**Numpy**

---


**Definition:** NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides powerful data structures, such as multi-dimensional arrays, and a large collection of mathematical functions that make it easier and faster to work with numerical data. It’s widely used in fields like data science, machine learning, scientific computing, and more.

In [35]:
#import Library
import numpy as np

**Array Creation Functions**

**1. **

**np.array():** Creates a NumPy array from a Python list or another array.

**np.zeros():** Creates an array filled with zeros.

**np.ones():** Creates an array filled with ones.

**np.arange():** Creates an array with evenly spaced values within a specified range.

**np.linspace():** Creates an array with a specified number of evenly spaced values between a start and end value.

**np.eye():** Creates an identity matrix.

In [ ]:
import numpy as np

# Creating a NumPy array from a Python list
print('Creating Array : ')
arr = np.array([1, 2, 3, 4])
print(arr)
#zero filling
print('Creating Array with 0 fill : ')
arr_zeros = np.zeros((3, 3))
print(arr_zeros)
#One filling
print('Creating Array with 1 fill : ')
arr_ones = np.ones((2, 3))
print(arr_ones)
# Creating an array with values from 0 to 9 (exclusive)
print('Creating Array with sequence value : ')
arr_range = np.arange(10)
print(arr_range)
# 5 evenly spaced numbers between 0 and 10
print('Creating Array with evenly spaced numbers between 0 and 10 : ')
arr = np.linspace(0, 10, 5)
print("Linspace:", arr)
print('Creating identity matrix : ')
arr = np.eye(3)  # 3x3 identity matrix
print("Creating opposite of Identity Matrix:\n", arr)
arr = np.fliplr(arr)
print("Matrix with ones on the opposite diagonal:\n", arr)

Creating Array : 
[1 2 3 4]
Creating Array with 0 fill : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Creating Array with 1 fill : 
[[1. 1. 1.]
 [1. 1. 1.]]
Creating Array with sequence value : 
[0 1 2 3 4 5 6 7 8 9]
Creating Array with evenly spaced numbers between 0 and 10 : 
Linspace: [ 0.   2.5  5.   7.5 10. ]
Creating identity matrix : 
Creating opposite of Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix with ones on the opposite diagonal:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


**2.** The **ndim** function in NumPy is an attribute that returns the number of dimensions (also called the rank) of a NumPy array

In [ ]:
# 1. Scalar (0D Array): A scalar is just a single number, so it has 0 dimensions.
import numpy as np
scalar = np.array(5)
print(scalar.ndim)  # Output: 0

# 2. 1D Array (Vector): A 1D array is like a list or vector.
vector = np.array([1, 2, 3, 4])
print(vector.ndim)  # Output: 1

# 3. 2D Array (Matrix): A 2D array is a matrix (rows and columns).
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim)  # Output: 2

# 4. 3D Array: A 3D array is a "cube" of numbers, with layers.
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube.ndim)  # Output: 3

# 5. Higher-Dimensional Array: For higher-dimensional arrays, ndim will return the number of axes.
high_dim_array = np.random.rand(2, 3, 4, 5)
print(high_dim_array.ndim)  # Output: 4 (4-dimensional array)

0
1
2
3
4


**3.** The **shape** function in NumPy is an attribute that returns the dimensions of an array.

In [ ]:
import numpy as np
print('A scalar is a single number, so the shape is an empty tuple')
scalar = np.array(5)
print(scalar.shape)  # Output: ()
print('A 1D array (vector) has only one axis')
vector = np.array([1, 2, 3, 4])
print(vector.shape)  # Output: (4,)  -> 4 elements in a 1D array

print('A 2D array (matrix) has two axes: rows and columns.')
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)  # Output: (2, 3)  -> 2 rows and 3 columns

print('A 3D array has three axes: depth, rows, and columns.')
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube.shape)  # Output: (2, 2, 2)  -> 2 layers, each with 2 rows and 2 columns

print('For higher-dimensional arrays, shape will return a tuple with the size of each dimension.')
high_dim_array = np.random.rand(2, 3, 4, 5)
print(high_dim_array.shape)  # Output: (2, 3, 4, 5) -> 2 layers, 3 rows, 4 columns, 5 depth


A scalar is a single number, so the shape is an empty tuple
()
A 1D array (vector) has only one axis
(4,)
A 2D array (matrix) has two axes: rows and columns.
(2, 3)
A 3D array has three axes: depth, rows, and columns.
(2, 2, 2)
For higher-dimensional arrays, shape will return a tuple with the size of each dimension.
(2, 3, 4, 5)


**Modifying the Shape:** **reshape()**


In [ ]:
# We can reshape an array to a different shape as long as the total number of elements remains the same.
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
reshaped_arr = arr.reshape(2, 3)  # 2 rows, 3 columns
print(reshaped_arr.shape)
print('Actual Arrary')
print(arr)
print('Reshaped')
print(reshaped_arr)


(6,)
(2, 3)
Actual Arrary
[1 2 3 4 5 6]
Reshaped
[[1 2 3]
 [4 5 6]]


In [ ]:
import random

random_float = random.random()
print(f"Random float between 0 and 1: {random_float}")


Random float between 0 and 1: 0.6568543881233202


In [ ]:
random_int = random.randint(1, 100)  # Random integer between 1 and 100
print(f"Random integer between 1 and 100: {random_int}")


Random integer between 1 and 100: 72


In [ ]:
choices = ['apple', 'banana', 'cherry', 'date']
random_choice = random.choice(choices)
print(f"Random choice from list: {random_choice}")


Random choice from list: date



**Create a 5x5 array filled with random integers from 0 to 10.**
1. Create a 1D array of shape (5,) that will be added to each row of the 5x5 array using broadcasting.
2. Multiply each column of the 5x5 array by a 1D array of shape (5,) using broadcasting.
3. Display the final result.

**Array Manipulation**
1. Create a 1D array with values from 1 to 20.
2. Reshape the array into a 4x5 matrix.
3. Flatten the reshaped matrix back into a 1D array.
4. ind the mean, standard deviation, and sum of the reshaped matrix.

**Date: 13-01-2025**

**NumPy - Indexing & Slicing**

Contents of ndarray object can be accessed and modified by indexing or slicing
We know that, items in ndarray object follows zero-based index.
Slicing is a process to extract a part of array.

In [6]:
import numpy as np
a = np.arange(10)
s = slice(2,7,2)
print (a[s])
#The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.
import numpy as np
a = np.arange(10)
s = a[2:7:2]
print (a[s])
# slice single item
a = np.arange(10)
b = a[5]
print (b)
# slice items starting from index

print (a[2:])

[2 4 6]
[2 4 6]
5
[2 3 4 5 6 7 8 9]


In [14]:
#Slicing in Mutlidimensional
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

# slice items starting from index
print ('Now we will slice the array from the index a[2:]' )
print(a[2:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[4 5 6]]


Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

In [19]:
# array to begin with
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print ('Our array is:' )
print(a)
print ('\n')

# this returns array of items in the second column
print ('The items in the second column are:' )
print (a[...,1] )
print ('\n')

# Now we will slice all items from the second row
print ('The items in the second row are:')
print (a[1,...])
print ('\n')

# Now we will slice all items from column 1 onwards
print ('The items column 1 onwards are:' )
print (a[...,1:])


Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


**Class Assignment: Create a NumPy array of 20 elements (from 1 to 20). Using slicing, extract:**

1. The first 5 elements.
2. The elements from index 5 to 15.
3. The last 3 elements

In [ ]:
#Write your code here

**Sorting Arrays in NumPy**

In [20]:
import numpy as np

arr = np.array([3, 1, 2, 5, 4])
arr.sort()
print("Sorted Array:", arr)

Sorted Array: [1 2 3 4 5]


In [21]:
#Sorting Along Specific Axes
import numpy as np

arr = np.array([[3, 2, 1], [6, 5, 4]])
axis0 = np.sort(arr, axis=0)
axis1 = np.sort(arr, axis=1)

print("Original Array:\n", arr)
print("Sorted Along Axis 0:\n", axis0)
print("Sorted Along Axis 1:\n", axis1)

Original Array:
 [[3 2 1]
 [6 5 4]]
Sorted Along Axis 0:
 [[3 2 1]
 [6 5 4]]
Sorted Along Axis 1:
 [[1 2 3]
 [4 5 6]]


In [22]:
#Partial Sorting Using partition()
import numpy as np

arr = np.array([3, 1, 2, 5, 4])
arr = np.partition(arr, 2)

print("Partitioned Array:", arr)

Partitioned Array: [1 2 3 5 4]


In [23]:
#Indirect Sorting Using argsort()
import numpy as np

arr = np.array([3, 1, 2, 5, 4])
sorted_indices = np.argsort(arr)

print("Indices that would sort the array:", sorted_indices)
print("Sorted Array Using Indices:", arr[sorted_indices])

Indices that would sort the array: [1 2 0 4 3]
Sorted Array Using Indices: [1 2 3 4 5]


In [27]:
#Sorting Structured Arrays
import numpy as np

arr = np.array([('John', 25), ('Alice', 30), ('Bob', 22)],
               dtype=[('name', 'U10'), ('age', 'i4')])
sorted_arr = np.sort(arr, order='age')

print("Sorted Structured Array:\n", sorted_arr)

Sorted Structured Array:
 [('Bob', 22) ('John', 25) ('Alice', 30)]


**Class Assignment:** Create a NumPy array of 10 random integers. Use np.argsort() to get the indices that would sort the array in ascending order, then print the sorted array using these indices.

In [ ]:
#Write your code here

**Handling Missing Data in Arrays**

In [28]:

import numpy as np

# Creating an array with missing values
arr = np.array([1, 2, np.nan, 4, np.nan, 6])

# Checking for missing values
is_nan = np.isnan(arr)

print("Array with Missing Values:\n", arr)
print("Missing Value Mask:\n", is_nan)

Array with Missing Values:
 [ 1.  2. nan  4. nan  6.]
Missing Value Mask:
 [False False  True False  True False]


In [29]:
#Removing Missing Data
import numpy as np

# Creating an array with missing values
arr = np.array([1, 2, np.nan, 4, np.nan, 6])

# Removing missing values
cleaned_arr = arr[~np.isnan(arr)]

print("Original Array:\n", arr)
print("Array with Missing Values Removed:\n", cleaned_arr)

Original Array:
 [ 1.  2. nan  4. nan  6.]
Array with Missing Values Removed:
 [1. 2. 4. 6.]


In [30]:
#Replacing Missing Data
import numpy as np

# Creating an array with missing values
arr = np.array([1, 2, np.nan, 4, np.nan, 6])

# Replacing missing values with zero
filled_arr = np.nan_to_num(arr, nan=0)

print("Original Array:\n", arr)
print("Array with Missing Values Replaced:\n", filled_arr)

Original Array:
 [ 1.  2. nan  4. nan  6.]
Array with Missing Values Replaced:
 [1. 2. 0. 4. 0. 6.]


In [34]:
#Interpolating Missing Data: Interpolating missing data involves estimating and filling in missing values within a dataset based on the surrounding data.
import numpy as np
from scipy.interpolate import interp1d

# Creating an array with missing values
arr = np.array([1, 2, np.nan, 4, np.nan, 6])

# Creating an index array
indices = np.arange(len(arr))

# Creating a mask for non-missing values
mask = ~np.isnan(arr)

# Performing linear interpolation
interp_func = interp1d(indices[mask], arr[mask], kind='linear')
filled_arr = interp_func(indices)

print("Original Array:\n", arr)
print("Array with Interpolated Missing Values:\n", filled_arr)

Original Array:
 [ 1.  2. nan  4. nan  6.]
Array with Interpolated Missing Values:
 [1. 2. 3. 4. 5. 6.]


**Class Assignment**: Create a 1D NumPy array of 10 integers and randomly replace 2 elements with np.nan. Replace all NaN values in the array with the number 0.