**Numpy**

---


**Definition:** NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides powerful data structures, such as multi-dimensional arrays, and a large collection of mathematical functions that make it easier and faster to work with numerical data. It’s widely used in fields like data science, machine learning, scientific computing, and more.

In [9]:
#import Library
import numpy as np

**Array Creation Functions**

**1. **

**np.array():** Creates a NumPy array from a Python list or another array.

**np.zeros():** Creates an array filled with zeros.

**np.ones():** Creates an array filled with ones.

**np.arange():** Creates an array with evenly spaced values within a specified range.

**np.linspace():** Creates an array with a specified number of evenly spaced values between a start and end value.

**np.eye():** Creates an identity matrix.

In [23]:
import numpy as np

# Creating a NumPy array from a Python list
print('Creating Array : ')
arr = np.array([1, 2, 3, 4])
print(arr)
#zero filling
print('Creating Array with 0 fill : ')
arr_zeros = np.zeros((3, 3))
print(arr_zeros)
#One filling
print('Creating Array with 1 fill : ')
arr_ones = np.ones((2, 3))
print(arr_ones)
# Creating an array with values from 0 to 9 (exclusive)
print('Creating Array with sequence value : ')
arr_range = np.arange(10)
print(arr_range)
# 5 evenly spaced numbers between 0 and 10
print('Creating Array with evenly spaced numbers between 0 and 10 : ')
arr = np.linspace(0, 10, 5)
print("Linspace:", arr)
print('Creating identity matrix : ')
arr = np.eye(3)  # 3x3 identity matrix
print("Creating opposite of Identity Matrix:\n", arr)
arr = np.fliplr(arr)
print("Matrix with ones on the opposite diagonal:\n", arr)

Creating Array : 
[1 2 3 4]
Creating Array with 0 fill : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Creating Array with 1 fill : 
[[1. 1. 1.]
 [1. 1. 1.]]
Creating Array with sequence value : 
[0 1 2 3 4 5 6 7 8 9]
Creating Array with evenly spaced numbers between 0 and 10 : 
Linspace: [ 0.   2.5  5.   7.5 10. ]
Creating identity matrix : 
Creating opposite of Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix with ones on the opposite diagonal:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


**2.** The **ndim** function in NumPy is an attribute that returns the number of dimensions (also called the rank) of a NumPy array

In [26]:
# 1. Scalar (0D Array): A scalar is just a single number, so it has 0 dimensions.
import numpy as np
scalar = np.array(5)
print(scalar.ndim)  # Output: 0

# 2. 1D Array (Vector): A 1D array is like a list or vector.
vector = np.array([1, 2, 3, 4])
print(vector.ndim)  # Output: 1

# 3. 2D Array (Matrix): A 2D array is a matrix (rows and columns).
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim)  # Output: 2

# 4. 3D Array: A 3D array is a "cube" of numbers, with layers.
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube.ndim)  # Output: 3

# 5. Higher-Dimensional Array: For higher-dimensional arrays, ndim will return the number of axes.
high_dim_array = np.random.rand(2, 3, 4, 5)
print(high_dim_array.ndim)  # Output: 4 (4-dimensional array)

0
1
2
3
4


**3.** The **shape** function in NumPy is an attribute that returns the dimensions of an array.

In [32]:
import numpy as np
print('A scalar is a single number, so the shape is an empty tuple')
scalar = np.array(5)
print(scalar.shape)  # Output: ()
print('A 1D array (vector) has only one axis')
vector = np.array([1, 2, 3, 4])
print(vector.shape)  # Output: (4,)  -> 4 elements in a 1D array

print('A 2D array (matrix) has two axes: rows and columns.')
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)  # Output: (2, 3)  -> 2 rows and 3 columns

print('A 3D array has three axes: depth, rows, and columns.')
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube.shape)  # Output: (2, 2, 2)  -> 2 layers, each with 2 rows and 2 columns

print('For higher-dimensional arrays, shape will return a tuple with the size of each dimension.')
high_dim_array = np.random.rand(2, 3, 4, 5)
print(high_dim_array.shape)  # Output: (2, 3, 4, 5) -> 2 layers, 3 rows, 4 columns, 5 depth


A scalar is a single number, so the shape is an empty tuple
()
A 1D array (vector) has only one axis
(4,)
A 2D array (matrix) has two axes: rows and columns.
(2, 3)
A 3D array has three axes: depth, rows, and columns.
(2, 2, 2)
For higher-dimensional arrays, shape will return a tuple with the size of each dimension.
(2, 3, 4, 5)


**Modifying the Shape:** **reshape()**


In [14]:
# We can reshape an array to a different shape as long as the total number of elements remains the same.
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
reshaped_arr = arr.reshape(2, 3)  # 2 rows, 3 columns
print(reshaped_arr.shape)
print('Actual Arrary')
print(arr)
print('Reshaped')
print(reshaped_arr)


(6,)
(2, 3)
Actual Arrary
[1 2 3 4 5 6]
Reshaped
[[1 2 3]
 [4 5 6]]


In [1]:
import random

random_float = random.random()
print(f"Random float between 0 and 1: {random_float}")


Random float between 0 and 1: 0.6568543881233202


In [3]:
random_int = random.randint(1, 100)  # Random integer between 1 and 100
print(f"Random integer between 1 and 100: {random_int}")


Random integer between 1 and 100: 72


In [7]:
choices = ['apple', 'banana', 'cherry', 'date']
random_choice = random.choice(choices)
print(f"Random choice from list: {random_choice}")


Random choice from list: date



**Create a 5x5 array filled with random integers from 0 to 10.**
1. Create a 1D array of shape (5,) that will be added to each row of the 5x5 array using broadcasting.
2. Multiply each column of the 5x5 array by a 1D array of shape (5,) using broadcasting.
3. Display the final result.

**Array Manipulation**
1. Create a 1D array with values from 1 to 20.
2. Reshape the array into a 4x5 matrix.
3. Flatten the reshaped matrix back into a 1D array.
4. ind the mean, standard deviation, and sum of the reshaped matrix.